name: test

on: [push]

jobs:
  test-integration-rootless:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      matrix:
        containerd: [main]
    env:
      CONTAINERD_VERSION: "${{ matrix.containerd }}"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: "Register QEMU (tonistiigi/binfmt)"
      run: docker run --privileged --rm tonistiigi/binfmt --install all
    - name: "Prepare (network driver=slirp4netns, port driver=slirp4netns)"
      run: DOCKER_BUILDKIT=1 docker build -t test-integration-rootless-port-slirp4netns --target test-integration-rootless-port-slirp4netns --build-arg CONTAINERD_VERSION=${CONTAINERD_VERSION} .
    - name: "Test    (network driver=slirp4netns, port driver=slirp4netns)"
      run: docker run -t --rm --privileged test-integration-rootless-port-slirp4netns go test -v ./cmd/nerdctl/... -run TestImageVerifyWithCosign
